version: '3'
services:
  app:
    build: .
    container_name: 'dashboard'
    command: php -S 0.0.0.0:80
    ports:
      - '81:80'
    volumes:
      - ./:/usr/src/myapp
    networks:
      - chama

networks:
  chama:
    driver: bridge 
    external: true 